%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosFileTransfer
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSFILETRANSFER_HRL).
-define(OE_COSFILETRANSFER_HRL, true).




-endif.


