%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyFilter_CallbackNotFound
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyFilter_CallbackNotFound').
-ic_compiled("4_3_3").


-include("CosNotifyFilter.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyFilter/CallbackNotFound:1.0",
                   "CallbackNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyFilter/CallbackNotFound:1.0".

%% returns name
name() -> "CosNotifyFilter_CallbackNotFound".



