%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyChannelAdmin_ConnectionAlreadyInactive
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyChannelAdmin_ConnectionAlreadyInactive').
-ic_compiled("4_3_3").


-include("CosNotifyChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyChannelAdmin/ConnectionAlreadyInactive:1.0",
                   "ConnectionAlreadyInactive",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyChannelAdmin/ConnectionAlreadyInactive:1.0".

%% returns name
name() -> "CosNotifyChannelAdmin_ConnectionAlreadyInactive".



