%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotifyFilter
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFYFILTER_HRL).
-define(OE_COSNOTIFYFILTER_HRL, true).




-endif.


