%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_VirtualFileSystem
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_VIRTUALFILESYSTEM_HRL).
-define(COSFILETRANSFER_VIRTUALFILESYSTEM_HRL, true).




-endif.


