%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_cos_naming
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COS_NAMING_HRL).
-define(OE_COS_NAMING_HRL, true).




-endif.


