%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime_TimeService
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_TIMESERVICE_HRL).
-define(COSTIME_TIMESERVICE_HRL, true).




-endif.


