%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_TimeBase
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosTime/src/TimeBase.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_TIMEBASE_HRL).
-define(OE_TIMEBASE_HRL, true).




-endif.


