%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosPropertyService_PropertyNotFound
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosPropertyService_PropertyNotFound').
-ic_compiled("4_3_3").


-include("CosPropertyService.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosPropertyService/PropertyNotFound:1.0",
                   "PropertyNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosPropertyService/PropertyNotFound:1.0".

%% returns name
name() -> "CosPropertyService_PropertyNotFound".



