%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ProxyPullSupplier
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_PROXYPULLSUPPLIER_HRL).
-define(COSEVENTCHANNELADMIN_PROXYPULLSUPPLIER_HRL, true).




-endif.


