%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_SupplierAdmin
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_SUPPLIERADMIN_HRL).
-define(COSEVENTCHANNELADMIN_SUPPLIERADMIN_HRL, true).




-endif.


