%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventComm_PullerS
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosEvent/src/cosEventApp.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCOMM_PULLERS_HRL).
-define(OE_COSEVENTCOMM_PULLERS_HRL, true).




-endif.


