%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventChannelAdmin
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCHANNELADMIN_HRL).
-define(OE_COSEVENTCHANNELADMIN_HRL, true).




-endif.


