%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventDomainAdmin_MemberIDSeq
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventDomainAdmin_MemberIDSeq').
-ic_compiled("4_3_3").


-include("CosEventDomainAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_sequence,tk_long,0}.

%% returns id
id() -> "IDL:omg.org/CosEventDomainAdmin/MemberIDSeq:1.0".

%% returns name
name() -> "CosEventDomainAdmin_MemberIDSeq".



