%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_PushConsumer
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_PUSHCONSUMER_HRL).
-define(COSNOTIFYCOMM_PUSHCONSUMER_HRL, true).




-endif.


