%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotifyComm
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFYCOMM_HRL).
-define(OE_COSNOTIFYCOMM_HRL, true).




-endif.


