%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosTimerEvent
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSTIMEREVENT_HRL).
-define(OE_COSTIMEREVENT_HRL, true).




-endif.


