%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: ETraP
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ETRAP_HRL).
-define(ETRAP_HRL, true).




-endif.


