%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_InvalidControl
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_InvalidControl').
-ic_compiled("4_3_3").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/InvalidControl:1.0",
                   "InvalidControl",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/InvalidControl:1.0".

%% returns name
name() -> "CosTransactions_InvalidControl".



