%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_erlang
%% Source: /tmp/buildd/erlang-16.b.2-dfsg/lib/ic/include/erlang.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_ERLANG_HRL).
-define(OE_ERLANG_HRL, true).




-endif.


